### ISSUE TITLE
Rebind a prefix in a chord

### ISSUE THREAD

**Issue by BlueDrink9** [darkstego/rebinder.el#3]
I would like to rebind my distribution's prefix "SPC c". 
I have this:
`(define-key evil-normal-state-map (kbd "C-d") (rebinder-dynamic-binding "SPC c"))`

However, this does not work. Instead, when I press C-d, emacs waits for more input (so C-d is seen as a prefix for _something_), but which-key shows no menu entries and pressing any of the keys that would otherwise come after SPC c claim to be undefined.

Is there a way to use rebinder for chord prefixes rather than just `C-` prefixes?

**Comment by darkstego** [comment]
`rebinder-key-binding` returns a keymap, and `rebinder-dynamic-binding` just allows that keymap to be evaluated late by making it a menu-item. It is mainly to be able to rebind prefixes keys that you cannot bind manually.

I have never used chord but I think you should be able to define the key to the target of the chord by a lookup. Might be something like `key-chord-lookup-key (kbd "SPC c")` instead of the rebinder portion of your example.
